//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDB.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MODDLEDbContext : DbContext
    {
        public MODDLEDbContext()
            : base("name=MODDLEDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Class> tbl_Class { get; set; }
        public virtual DbSet<tbl_ClassParticipent> tbl_ClassParticipent { get; set; }
        public virtual DbSet<tbl_Parent> tbl_Parent { get; set; }
        public virtual DbSet<tbl_Post> tbl_Post { get; set; }
        public virtual DbSet<tbl_Result> tbl_Result { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Schedule> tbl_Schedule { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
        public virtual DbSet<tbl_Subject> tbl_Subject { get; set; }
        public virtual DbSet<tbl_Teacher> tbl_Teacher { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
    }
}
