//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDB.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comment
    {
        public int comment_id { get; set; }
        public string comment_text { get; set; }
        public Nullable<int> UserID { get; set; }
        public string comment_Time { get; set; }
        public Nullable<int> postID { get; set; }
        public Nullable<int> classID { get; set; }
    
        public virtual tbl_Post tbl_Post { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
