//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDB.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Schedule
    {
        public int sheduleId { get; set; }
        public string date { get; set; }
        public string room { get; set; }
        public string teacher { get; set; }
        public string session { get; set; }
        public string section { get; set; }
        public string subjectName { get; set; }
        public string time { get; set; }
        public string deppt { get; set; }
    }
}
